sudo: required
language: python
dist: trusty
python:
    - '3.5'

env:
  - DEPLOY_USER=autocrypt DEPLOY_SERVER="autocrypt.org"

addons:
  apt:
    packages:
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-latex-extra
    - latexmk
    - inkscape

before_install:
  - openssl aes-256-cbc -K $encrypted_ee89c1e228aa_key -iv $encrypted_ee89c1e228aa_iv -in autocrypt.id_rsa.enc -out $TRAVIS_BUILD_DIR/id_rsa -d
  - chmod 600 $TRAVIS_BUILD_DIR/id_rsa
  - md5sum $TRAVIS_BUILD_DIR/id_rsa
install:
  - pip install sphinx

script:
  - cd doc
  - make html
  - make latexpdf
  - cd ..

deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    branch: ci/render


#notifications:
#  irc:
#    channels:
#      - "chat.freenode.net#autocrypt"
#    on_success: change
#    on_failure: change
#    skip_join: true
#  email:
#    - pytest-commit@python.org
